### ISSUE TITLE
Visual glitch with Shadersmodcore + TFC

### ISSUE THREAD

**Issue by lightning02** [FFS2309/Shadersmodcore#3]
Hello, I've encountered this graphical glitch adding Shaders Mod Core on Terrafirmacraft.
Grafic card and drivers info aren't really needed since I've tryed this on 2 differents computers with respectively Nvidia and AMD dedicated gpu so the problem seems to be related with shaders mod (or TFC eventually).
I'm using latest version of forge 1.7.10 with latest version of Shaders Mod Core and Terrafirmacraft with java 32 + 64 bit update 92.
As you see the problem is a visual glitch of the thermal vapor that comes out from spa.
![1](https://cloud.githubusercontent.com/assets/11884147/15609418/39fd8d00-2420-11e6-915e-5636a003cec5.png)
![2](https://cloud.githubusercontent.com/assets/11884147/15609430/4af1b7da-2420-11e6-9c8d-5524c809d4da.png)

**Comment by FFS2309** [comment]
Sorry but I'm not working on the shaders mod :( I would suggest you to ask karyonix on the [shaders mod thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286604-shaders-mod-updated-by-karyonix)
